# Generated by Django 4.2.23 on 2025-07-28 08:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_ofBirth', models.DateField()),
                ('subject', models.CharField(choices=[('MPC', 'Math Physic Computer'), ('MEG', 'Math Economy Geography'), ('MCE', 'Math Computer Economy'), ('MCB', 'Math Chemistry Biology')], default='MPC', max_length=50)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('image', models.ImageField(upload_to='profile_pictures')),
            ],
        ),
    ]
